### ISSUE TITLE
[Bug] B-06 replication can commit after authority changes in the final check-to-put gap

### ISSUE THREAD

**Issue by unikdahal** [unikdahal/resumable-driver#695]
## Summary

`RecoveryBlobReplicateHandler` rechecks authority after peer fetch, but the check and destination `put` are still separate operations. An authoritative epoch/owner/state refresh can interleave after the second check and before/during the durable write, allowing the stale replication to commit.

Reviewed at `1927a3912fec3046dc95dc78e6997f016126a917` as a follow-up to closed B-06/D-06. This is independent of #634: #634 covers reusing the entry timestamp; this race remains even after sampling a fresh timestamp.

## Evidence

- `RecoveryBlobReplicateHandler.java:81-84` calls `requireAuthority(...)`, returns from the synchronized handler check, then calls `context.blobs().put(...)` separately.
- `requireAuthority` at lines 98-107 delegates to `RecoveryFenceHandler.requireMutationAuthority`, whose monitor is released on return.
- `RecoveryMutationGate.withAuthority` exists to close this exact check-to-mutation window, but replication does not use it.
- Destination `put` performs blocking filesystem operations, making the interleaving observable.

## Reproduction schedule

1. Complete peer fetch and validation under epoch/owner `(1,A)`.
2. Let the post-fetch `requireAuthority` check succeed, then pause before destination mutation.
3. Install authoritative epoch/owner `(2,B)` or a non-ACTIVE state.
4. Resume `blobs().put`.

The stale epoch-1 request commits and reports success after epoch 2/revoke has won.

## Impact

Fenced replication can mutate durable worker storage after ownership changes. The artifact can then be reported as possessed and counted in replica/quorum decisions despite being written without current authority.

## Expected behavior

Use a fresh monotonic time after peer I/O and bind the final authority check atomically to the destination mutation with the common authority gate or equivalent lock protocol.

## Acceptance criteria

- A deterministic latch-based test proves a refresh between final admission and `put` prevents the stale commit.
- Time-only expiry during peer fetch remains covered as in #634.
- Lock ordering is documented and cannot deadlock authoritative refreshes with blob-store operations.

**Comment by unikdahal** [comment]
Reconfirmed during the #691/B-05 deep review at current `resumable-v1` base `3e04609961a2bf41e1039aef9a1c07f45a31fa2d`: B-06 still performs its fresh post-fetch `requireMutationAuthority` check and destination `context.blobs().put(...)` as separate operations, so the same final check-to-put refresh interleaving remains possible. This is out of scope for #691 and I am not modifying B-06 here. The B-05 fix in PR #786 uses the common `RecoveryMutationGate` and provides a directly reusable pattern for #695; #634 remains distinct (fresh-time sampling during peer fetch).

**Comment by unikdahal** [comment]
Independent B-06 CI finding reproduced while reviewing #689 on 2026-08-30. This is directly relevant to this OPEN issue because #695's expected correction is to use `RecoveryMutationGate`, but the current B-06 dedicated workflow cannot compile the already-landed B-05 use of that class.

Exact evidence:
- PR under review: #787
- head: `5e14e0f9ff2213d55ecd45a1f5518b22ee81bcf4`
- base: `21335121f6d3120dedbbe1079c1f0822536d3c65`
- B-06 workflow run: `33292367050`
- job: `99206155099`
- whitespace: PASS
- B-06 Spotless: PASS
- compile dependency build: PASS
- affected-suite step: FAIL during javac, before tests

The explicit source list in `.github/workflows/b06-fenced-replicate.yml` includes `RecoveryBlobRpcHandler.java` but omits `RecoveryMutationGate.java`. Since B-05/#691 changed `RecoveryBlobRpcHandler.Context` to own a `RecoveryMutationGate`, javac fails with three `cannot find symbol: class RecoveryMutationGate` errors at `RecoveryBlobRpcHandler.java` around lines 369/376/385.

This is not caused by #689's lease reconciliation semantics: the failure is a static source-closure omission in the B-06 task-dedicated workflow on the current base. #689 will not edit B-06's workflow because that would violate task CI ownership. When #695 updates B-06 to use the common mutation gate, its dedicated workflow should add `RecoveryMutationGate.java` to the explicit compile closure as well.

**Comment by unikdahal** [comment]
## Final closure / post-merge verification

#695 is fully resolved by merged PR #796.

- PR: https://github.com/unikdahal/resumable-driver/pull/796
- Squash merge commit: `5832da4c787ad06612c128a08ea65e528e8b916a`
- Issue state: closed / completed

### Merged behavior

`RecoveryBlobReplicateHandler` now keeps peer I/O outside the authority monitor, samples fresh monotonic time after peer validation, and uses `RecoveryMutationGate.withAuthority(...)` to make the final authority check atomic with destination `put`. A refresh can therefore linearize before the final gate and fence the request, or after the guarded put; it cannot win in the former check-to-put gap.

The deterministic issue-695 suite covers both final-boundary orderings, exact post-fetch lease expiry, destination `IOException`, and empty peer payload. Existing B-06 coverage retains the #634 time-only-expiry case and two-worker E/epoch/digest replication behavior.

### Post-merge gate evidence on the actual target commit

B-06 push run: https://github.com/unikdahal/resumable-driver/actions/runs/33293017494

Job: `99207831526` — **SUCCESS**

- whitespace: PASS
- Spotless: PASS (`BUILD SUCCESS`)
- isolated B-06 dependency/source closure: PASS, including `RecoveryMutationGate.java`
- affected suites: PASS — JUnit 4.13.2 printed `............`, `Time: 0.207`, exact `OK (12 tests)`; workflow separately grepped the exact count
- `ConfigurationSuite-if-conf`: PASS / N/A — `N/A - B-06 changes no Celeborn configuration surface.`
- evidence artifact: `b06-affected-suite-evidence`, ID `9726565891`, 214 bytes, SHA-256 `f0dcbc39485919458838045922e1891b532edb8bc7e4a72d7d5e2cccfb71a6b5`

Additional post-merge checks on the same commit:
- Generic CI run `33293017533`: **SUCCESS**
- Z-10 license/header run `33293017498`: **SUCCESS**
- Z-13 dependency review run `33293017522`: known repository-wide pre-existing failure on the Iceberg baseline paths; already routed to OPEN #747 and not introduced by #796.

### Out-of-scope follow-ups routed

- OPEN #696: B-06 source-worker identity bound; the independent #695 review evidence was added there rather than changing identity validation in this fix.
- OPEN #747: repository-wide Z-13 Iceberg baseline debt; current occurrence recorded there.
- NEW OPEN #797: the successful post-merge B-06 job emitted the Node-20-runtime deprecation warning for `actions/upload-artifact@v4`. No OPEN issue covered the B-06 warning; closed #766 is G-33-specific, so a new B-06 follow-up was created instead of reopening/commenting on it.

No further #695 correctness follow-up is required.
